import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/_organisms/header/Header';
import localFont from 'next/font/local';

const league = localFont({
  src: '../public/assets/font/LeagueSpartan-VariableFont_wght.ttf',
  variable: '--font-league',
  weight: '100 900',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${league.variable}`}>
      <body className=''>
        <Header />
        {children}
      </body>
    </html>
  );
}
